Improved module/package docstrings
sodascience/metasyn pull request #226
Opened 2024-01-04 12:03 UTC by Samuwhale

This is a first step towards improving the docstrings. Proper docstrings will help the automatically generated API be more usable and informative, it will also help using the package itself.

Next step will be class and function docstrings. But for now, module level docstrings.

I have tried to keep them under 79 characters per line, but in some cases an exception had to be made.

2024-01-04 14:02 UTC, qubixes requested changes
Thanks a lot! I updated the PR  a bit already to remove some linting errors. I really like the new docstrings, more descriptive, without being too verbose! I have added some small comments/suggestions, but nothing major.

2024-01-04 14:02 UTC, qubixes commented on metasyn/var.py
> +    MetaVar is a structure that holds all metadata needed to generate a
Would be interesting to rename to MetaSeries at some point?

2024-01-05 11:26 UTC, Samuwhale commented on metasyn/distribution/continuous.py
> +"""Module implementing uniform (floating point) distributions."""
big whoops

2024-01-05 11:29 UTC, Samuwhale commented on metasyn/__init__.py
> +A MetaFrame is essentially a fitted model that characterizes the structure of
Sounds good to me!

2024-01-05 11:32 UTC, Samuwhale commented on metasyn/__init__.py
> +2. Serialization: Metasyn can export a MetaFrame into an easy to read GMF file.
Agreed!

2024-01-05 11:39 UTC, Samuwhale commented on metasyn/distribution/__init__.py
> +generating synthetic data, and other functionality specific to the type of
I wrote it thinking that distributions might have specific functionality. I do realise however that that is not the case. I'll rewrite it.

2024-01-05 11:50 UTC, Samuwhale commented on metasyn/distribution/__init__.py
> +generating synthetic data, and other functionality specific to the type of
I've changed it a bit, does this make more sense?

2024-01-05 11:50 UTC, Samuwhale commented
I have applied the changes! 

I will also create an issue to update the frontpage of the docs to reflect the content of the metasyn `__init__.py`, and to create an issue to potentially rename MetaVar to MetaSeries.

2024-01-05 15:57 UTC, qubixes approved these changes
Looks good now!

2024-01-08 07:40 UTC, merged